#!/usr/bin/env python3
"""
Пример автогенератора документации для тестирования системы определения авторства.
Этот скрипт создает документацию с маркерами автогенерации.
"""

import os
import sys
import json
from datetime import datetime

def create_api_documentation():
    """Генерирует документацию API с маркерами автогенерации"""
    
    output_dir = "docs/auto_generated"
    os.makedirs(output_dir, exist_ok=True)
    
    api_doc_content = f"""<!-- AUTO-GENERATED -->

*Автоматически сгенерировано скриптом example_doc_generator.py*  
*Дата генерации: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*


Данная документация автоматически создана на основе анализа кода.


Получение списка пользователей.

**Параметры:**
- `limit` (int): Максимальное количество записей
- `offset` (int): Смещение для пагинации

**Ответ:**
```json
{{
  "users": [],
  "total": 0
}}
```

Создание нового пользователя.

**Тело запроса:**
```json
{{
  "name": "string",
  "email": "string"
}}
```


```json
{{
  "id": "integer",
  "name": "string", 
  "email": "string",
  "created_at": "datetime"
}}
```

---
*Этот файл создан автоматически. Не редактируйте вручную.*
"""

    api_doc_path = os.path.join(output_dir, "api_documentation.md")
    with open(api_doc_path, 'w', encoding='utf-8') as f:
        f.write(api_doc_content)
    
    return api_doc_path

def create_changelog():
    """Генерирует файл изменений с маркерами автогенерации"""
    
    output_dir = "docs/auto_generated"
    os.makedirs(output_dir, exist_ok=True)
    
    changelog_content = f"""# AUTO-GENERATED

*Generated by example_doc_generator.py*  
*Дата генерации: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*


- Новая система автогенерации документации
- Улучшенное определение авторства файлов
- Поддержка русской навигации

- Исправлены битые ссылки в документации
- Улучшена производительность сканирования файлов

- Обновлена структура Content.json
- Переработана система навигации

---
*This file was automatically generated. Do not edit manually.*
"""

    changelog_path = os.path.join(output_dir, "CHANGELOG_AUTO.md")
    with open(changelog_path, 'w', encoding='utf-8') as f:
        f.write(changelog_content)
    
    return changelog_path

def create_metrics_report():
    """Генерирует отчет метрик с маркерами автогенерации"""
    
    output_dir = "docs/auto_generated"
    os.makedirs(output_dir, exist_ok=True)
    
    metrics_content = f"""<!-- AUTO-GENERATED -->

*Автоматически сгенерировано системой update-docs*  
*Время генерации: {datetime.now().isoformat()}*


| Тип файла | Количество | Размер (KB) |
|-----------|------------|-------------|
| Markdown  | 45         | 1,234       |
| Python    | 12         | 567         |
| JSON      | 3          | 89          |


| Тип автора | Файлов | Процент |
|------------|--------|---------|
| Human      | 38     | 84%     |
| AI         | 5      | 11%     |
| Generator  | 2      | 5%      |


- **Покрытие документацией**: 87%
- **Битых ссылок**: 0
- **Дубликатов заголовков**: 3

---
*Generated by update-docs - Автоматически сгенерировано*
"""

    metrics_path = os.path.join(output_dir, "metrics_report.md")
    with open(metrics_path, 'w', encoding='utf-8') as f:
        f.write(metrics_content)
    
    return metrics_path

def create_generator_registry():
    """Создает реестр автогенераторов для отслеживания"""
    
    registry = {
        "generators": [
            {
                "name": "example_doc_generator.py",
                "description": "Пример автогенератора документации",
                "output_files": [
                    "docs/auto_generated/api_documentation.md",
                    "docs/auto_generated/CHANGELOG_AUTO.md", 
                    "docs/auto_generated/metrics_report.md"
                ],
                "markers": [
                    "<!-- AUTO-GENERATED -->",
                    "# AUTO-GENERATED",
                    "*Автоматически сгенерировано*",
                    "*Generated by example_doc_generator.py*"
                ],
                "last_run": datetime.now().isoformat()
            }
        ]
    }
    
    registry_path = "docs/auto_generated/generator_registry.json"
    with open(registry_path, 'w', encoding='utf-8') as f:
        json.dump(registry, f, indent=2, ensure_ascii=False)
    
    return registry_path

def main():
    """Главная функция автогенератора"""
    print("🤖 Запуск автогенератора документации...")
    
    generated_files = []
    
    api_doc = create_api_documentation()
    generated_files.append(api_doc)
    print(f"✅ Создан: {api_doc}")
    
    changelog = create_changelog()
    generated_files.append(changelog)
    print(f"✅ Создан: {changelog}")
    
    metrics = create_metrics_report()
    generated_files.append(metrics)
    print(f"✅ Создан: {metrics}")
    
    registry = create_generator_registry()
    generated_files.append(registry)
    print(f"✅ Создан: {registry}")
    
    print(f"\n🎉 Автогенерация завершена! Создано {len(generated_files)} файлов:")
    for file_path in generated_files:
        print(f"  - {file_path}")
    
    print("\n📝 Все файлы помечены маркерами автогенерации для корректного определения авторства.")

if __name__ == "__main__":
    main()
